### PR TITLE
Custom Message View

### PR DESCRIPTION
**Pull request by Jam155**
I've been using your Chat UI in an application that I've been building and I've made some changes to it that I think would be useful. Never really done a pull request before so I'm not quite sure how this goes but here's a list of updates that I've made.

- Separated out the ViewHolder and ViewAdapters into their own classes.
- Created a Abstract Message View class that all message views must inherit from.
- Made your views have a class wrapper so they can be passed around more easily and also conform to our abstract class mandate.
- Created a view builder that can be given to the chat-ui constructor to build the views required.
- Added some documentation to some of the classes and methods. Mainly my own since I know exactly what happens in those ones.

If you let me know if there are any changes that you'd like making in order to accept this pull request I'd be grateful, it should be up to date with your master branch at this point in time.

I'm going to be doing quite a lot of work on android chat stuff over the coming months and if you don't mind I'd certainly be happy to implement any of the features from that into this library.

Thanks for your time.

### CODE REVIEW

**Comment by timigod** [comment]
Will give it a look @Jam155, might be a day or two or three.

**Comment by Jam155** [comment]
@timigod Awesome, thanks!

**Review by robertmain — APPROVED** [review]

**Comment by Jam155** [comment]
@timigod Did you get a chance to go through this yet? Thanks.

**Comment by timigod** [comment]
@Jam155 yes I have. Will merge soon. I'm trying to set up JitPack for this first.

**Review by timigod — APPROVED** [review]

**Comment by timigod** [comment]
@Jam155 merged and 0.1.3 is out. I'm also adding you the repo as a collaborator. I really appreciate the work.

**Comment by Jam155** [comment]
Awesome! Thanks,

**Pull request merged**
