### PR TITLE
delete messages #6: clear messages and remove message by index

### PR DESCRIPTION
**Pull request by r-cohen**

### CODE REVIEW

**Comment by r-cohen** [comment]
@timigod thanks for this merge. can we expect a new release?

**Comment by timigod** [comment]
@phearme tomorrow. Thanks for the PR!

**Comment by r-cohen** [comment]
@timigod hey! do we have a new release ready?

**Comment by timigod** [comment]
Yes there is, v0.1.2

**Comment by r-cohen** [comment]
Thanks.

**Pull request merged**
